<?xml version="1.0"?>
<package format="3">
  <name>pointcloud_map_projection</name>
  <version>0.1.0</version>
  <description>Converts a saved Fast-LIO2 PCD map into a 2D OccupancyGrid map.</description>
  <maintainer email="ros@example.com">ROS2_FOR_SCOUT_MINI</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
